// workshopConstants.js
export const WORKSHOP_LIST_REQUEST = 'WORKSHOP_LIST_REQUEST';
export const WORKSHOP_LIST_SUCCESS = 'WORKSHOP_LIST_SUCCESS';
export const WORKSHOP_LIST_FAIL = 'WORKSHOP_LIST_FAIL';
export const WORKSHOP_DETAILS_REQUEST = 'WORKSHOP_DETAILS_REQUEST';
export const WORKSHOP_DETAILS_SUCCESS = 'WORKSHOP_DETAILS_SUCCESS';
export const WORKSHOP_DETAILS_FAIL = 'WORKSHOP_DETAILS_FAIL';
export const LOCATION_DETAILS_REQUEST = 'LOCATION_DETAILS_REQUEST';
export const LOCATION_DETAILS_SUCCESS = 'LOCATION_DETAILS_SUCCESS';
export const LOCATION_DETAILS_FAIL = 'LOCATION_DETAILS_FAIL';
export const HOBBY_DETAILS_REQUEST = 'HOBBY_DETAILS_REQUEST';
export const HOBBY_DETAILS_SUCCESS = 'HOBBY_DETAILS_SUCCESS';
export const HOBBY_DETAILS_FAIL = 'HOBBY_DETAILS_FAIL';
export const WORKSHOP_DETAILS_RESET = 'WORKSHOP_DETAILS_RESET';

